name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v5
        with:
          release-type: node

      - name: Trigger npm publish
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: gh workflow run publish.yml --repo '${{ github.repository }}' --ref main -f tag_name='${{ steps.release.outputs.tag_name }}'
        env:
          GH_TOKEN: ${{ github.token }}
